export { default as register } from './register.js'
export { default as login } from './login.js'
export { default as forgotPassword } from './forgotPassword.js'
export { default as survey } from './survey.js'
export { default as changeName } from './changeName.js'
export { default as user } from './user.js'